# gitzone standard
image: hosttoday/ht-docker-node:npmci

cache:
  paths:
  - .yarn/
  key: "$CI_BUILD_STAGE"

stages:
- test
    
testSTABLE:
  stage: test
  script:
    - npmci test stable
    - npmci trigger
  coverage: /\d+.?\d+?\%\s*coverage/
  tags:
    - docker
